import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import Footer from "./_comp/footer/Footer";
import { Navbar } from "./_comp/navbar/Navbar";
import TopUtilityBar from "./_comp/firstNavbar/FirstNavbar";
import { ToastContainer } from "react-toastify";
import MyProvider from "./_comp/MyProvider/MyProvider";
import QueryProvider from "./_comp/queryProvider/QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative">
        <QueryProvider>
    <MyProvider>
      <ToastContainer />

      <TopUtilityBar />
      <Navbar />

      {children}

      <Footer />
    </MyProvider>
  </QueryProvider>
        </body>
    </html>
  );
}
